services:
  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test

  js:
    build: ./js
    volumes:
      - ./js/src:/usr/share/nginx/html
    ports:
      - "8081:80"